name: Checks

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 19.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Lint
      run: |
        npm i -g eslint
        npm run lint
      env:
        CI: true
    - name: npm ci
      run: npm ci
    - name: Build the stack
      run: docker-compose up -d
    - name: test
      run: npm test
